### ISSUE TITLE
Bug: Decision "Mare Occidentis Nostrum" not WAD

### ISSUE THREAD

**Issue by tbg2021** [Savolainen5/The-Heirs-to-Aquitania#1]
Tried doing this earlier today, but puppeting didn't actually trigger the requirements for any individual city/country. Had to console all the capitals over manually for it to fire.

**Comment by Savolainen5** [comment]
> Tried doing this earlier today, but puppeting didn't actually trigger the requirements for any individual city/country. Had to console all the capitals over manually for it to fire.

Thanks for the report, I've pushed a fix!
